import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class QuestionService {
  private questions = {
    javascript: [
      'Tell me about yourself.',
      'What is your hobby?',
      'What is closure in JavaScript?',
      'Explain the event loop in JavaScript.',
      'What are JavaScript promises?',
      'What is the difference between == and ===?',
      'What is hoisting in JavaScript?',
      'What is a prototype in JavaScript?',
      'Explain async and await in JavaScript.',
      'What are arrow functions in JavaScript?',
      'What is localStorage in JavaScript?',
      'Explain the difference between var, let, and const.',
    ],
    java: [
      'Tell me about yourself.',
      'What is your hobby?',
      'What are the main features of Java?',
      'What is JVM, JRE, and JDK?',
      'Explain the difference between method overloading and method overriding.',
      'What is the difference between an abstract class and an interface?',
      'What is a constructor in Java?',
      'What are static methods in Java?',
      'What is multithreading in Java?',
      'Explain the concept of garbage collection in Java.',
      'What is the difference between ArrayList and LinkedList?',
      'What is the purpose of the final keyword in Java?',
    ],
    angular: [
      'Tell me about yourself.',
      'What is your hobby?',
      'What is Angular?',
      'What are components in Angular?',
      'What is Angular CLI?',
      'What are directives in Angular?',
      'What is dependency injection in Angular?',
      'What is a service in Angular?',
      'What is RxJS in Angular?',
      'What is change detection in Angular?',
      'What is lazy loading in Angular?',
      'What is the difference between reactive forms and template-driven forms?',
    ],
    html: [
      'Tell me about yourself.',
      'What is your hobby?',
      'What is HTML?',
      'What are semantic tags in HTML?',
      'What is the difference between div and span?',
      'What are meta tags in HTML?',
      'What is the difference between HTML and XHTML?',
      'What is the use of the DOCTYPE declaration?',
      'What are HTML5 new elements?',
      'What is the difference between localStorage, sessionStorage, and cookies?',
      'What is the purpose of the <iframe> tag?',
      'What is the difference between absolute and relative links?',
    ],
    css: [
      'Tell me about yourself.',
      'What is your hobby?',
      'What is CSS?',
      'What is the difference between relative, absolute, and fixed positioning in CSS?',
      'What is Flexbox in CSS?',
      'What is Grid in CSS?',
      'What are pseudo-classes and pseudo-elements?',
      'What is the difference between inline, block, and inline-block elements?',
      'What is the difference between em, rem, and px in CSS?',
      'What is the purpose of media queries in CSS?',
      'What is z-index in CSS?',
      'How does the box model work in CSS?',
    ],
    react: [
      'Tell me about yourself.',
      'What is your hobby?',
      'What is React?',
      'What are components in React?',
      'What is JSX in React?',
      'What is the difference between functional and class components?',
      'What is the use of useState in React?',
      'What is the use of useEffect in React?',
      'What are props in React?',
      'What is the virtual DOM in React?',
      'What is React Router?',
      'What are React hooks?',
    ],
    python: [
      'Tell me about yourself.',
      'What is your hobby?',
      'What are Python key features?',
      'What is the difference between Python 2 and Python 3?',
      'What are Python lists and tuples?',
      'What is the difference between mutable and immutable types in Python?',
      'What is a lambda function in Python?',
      'What is the difference between deep copy and shallow copy in Python?',
      'What is Python’s GIL (Global Interpreter Lock)?',
      'What are Python decorators?',
      'What is the difference between range() and xrange() in Python?',
    ],
    typescript: [
      'Tell me about yourself.',
      'What is your hobby?',
      'What is TypeScript?',
      'What are the main advantages of TypeScript over JavaScript?',
      'What are interfaces in TypeScript?',
      'What is the difference between let, var, and const in TypeScript?',
      'What is TypeScript’s type inference?',
      'What are generics in TypeScript?',
      'What is the difference between any and unknown in TypeScript?',
      'What is TypeScript’s enum feature?',
      'What are modules in TypeScript?',
      'How does TypeScript handle null and undefined?',
    ],
    dsa: [
      'Tell me about yourself.',
      'What is your hobby?',
      "Let's dive into the world of Data Structures and Algorithms. Ready to answer some fundamental questions? What is an array, and how is it different from a linked list?",
      'What is a binary tree, and how does it differ from a binary search tree?',
      'Explain the difference between depth-first search and breadth-first search.',
      'What are stacks and queues? Can you explain with examples?',
      'What is a hash table, and how does it work?',
      'What is dynamic programming? Can you provide an example?',
      'What are the different types of sorting algorithms? Can you explain quicksort?',
      'What is a graph, and how do we represent it?',
      'Explain the concept of time complexity and Big O notation.',
      'What is a heap, and how is it used?',
    ],
  };

  getQuestions() {
    return this.questions;
  }
}
